name: Deploy Laravel App

on:
  push:
    branches:
      - master # Agar aapki branch ka naam master hai toh yahan master likhein

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/laravel-aws-app
          
          # 1. Server par permissions check aur fix karein taaki pull block na ho
          sudo chown -R ec2-user:nginx /var/www/laravel-aws-app
          
          # 2. Hard pull karein (Force reset aur pull)
          git fetch --all
          git reset --hard origin/main
          git pull origin main --force
          
          # 3. Cache completely clear karein
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache